- name: run show version on remote devices
  cisco.ios.ios_command:
    commands: show version

- pause:
    seconds: 40

- name: fetch final config
  ansible.netcommon.cli_command:
    command: "copy http://{{ config_fileserver }}/{{ inventory_hostname }}.cfg startup-config"

- name: reboot device
  ansible.netcommon.cli_command:
    command: "reload"
    prompt:
      - "Save"
      - "confirm"
    answer:
      - "no"
      - "y"
#    check_all: True
